#ifndef LIBSYNEXENS3_VERSION_IN_H
#define LIBSYNEXENS3_VERSION_IN_H

#define LIBSYNEXENS3_MAJOR 0
#define LIBSYNEXENS3_MINOR 2
#define LIBSYNEXENS3_REVISION 5

#define LIBSYNEXENS3_BUILD "202208161637"
#define LIBSYNEXENS3_BUILD_TIMESTAMP_YEAR 2022
#define LIBSYNEXENS3_BUILD_TIMESTAMP_MON 08
#define LIBSYNEXENS3_BUILD_TIMESTAMP_DAY 16
#define LIBSYNEXENS3_BUILD_TYPE "alpha"


#define LIBSYNEXENS3_RECOMMENDED_CS30_FIRMWARE_VERSION_MAJOR 0
#define LIBSYNEXENS3_RECOMMENDED_CS30_FIRMWARE_VERSION_MINOR 7
#define LIBSYNEXENS3_RECOMMENDED_CS30_FIRMWARE_VERSION_REVISION 0
#define LIBSYNEXENS3_RECOMMENDED_CS30_FIRMWARE_VERSION_TIMESTAMP "20220810"

#define LIBSYNEXENS3_RECOMMENDED_CS20_FIRMWARE_VERSION "2108200201"

#endif


